; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
framework = arduino
board_build.core = earlephilhower
board_build.filesystem_size = 0.5m
monitor_speed = 115200

lib_deps =
    jgromes/RadioLib
    jsc/ArduinoLog
    maxpowel/Json Writer
    adafruit/Adafruit Unified Sensor
    adafruit/Adafruit INA3221 Library
    adafruit/Adafruit BME280 Library
    adafruit/Adafruit BMP280 Library
    northernwidget/DS3231
    robtillaart/TCA9555
    #https://github.com/iontodirel/libaprsroute.git
    #https://github.com/iontodirel/libaprs.git ajouté en lib avec git submodule car dans cette lib il y a un fichier tools/symbols/main.cpp qui ne compile pas et que pio veut absolument compiler
    #https://github.com/meshcore-dev/MeshCore.git
    #https://github.com/torlando-tech/microReticulum

build_flags = -Wno-unused-variable
              -fexceptions
              -D RP2040_PLATFORM
              -DRADIOLIB_EXCLUDE_LR11X0=1
              -DRADIOLIB_EXCLUDE_NRF24=1
              -DRADIOLIB_EXCLUDE_RF69=1
              -DRADIOLIB_EXCLUDE_SX1231=1
              -DRADIOLIB_EXCLUDE_SX1233=1
              -DRADIOLIB_EXCLUDE_SI443X=1
              -DRADIOLIB_EXCLUDE_SX128X=1
              -DRADIOLIB_EXCLUDE_RFM2X=1
              -DRADIOLIB_EXCLUDE_AFSK=1
              -DRADIOLIB_EXCLUDE_BELL=1
              -DRADIOLIB_EXCLUDE_HELLSCHREIBER=1
              -DRADIOLIB_EXCLUDE_MORSE=1
              -DRADIOLIB_EXCLUDE_RTTY=1
              -DRADIOLIB_EXCLUDE_SSTV=1
              -DRADIOLIB_EXCLUDE_DIRECT_RECEIVE=1
              -DRADIOLIB_EXCLUDE_BELL=1
              -DRADIOLIB_EXCLUDE_PAGER=1
              -DRADIOLIB_EXCLUDE_FSK4=1
              -DRADIOLIB_EXCLUDE_APRS=1
              -DRADIOLIB_EXCLUDE_LORAWAN=1
              -DRADIOLIB_EXCLUDE_LORAWAN=1
              -D__FREERTOS=1
;              -DconfigMINIMAL_STACK_SIZE=512

[env:pico]
board = pico