#ifndef CUBECELL_MONITORING_CONFIG_H
#define CUBECELL_MONITORING_CONFIG_H

#include <ArduinoLog.h>

#define WireUsed Wire

#define USE_RF true

#define RF_FREQUENCY 433775000 // Hz
#define LORA_BANDWIDTH 0 // [0: 125 kHz,
//  1: 250 kHz,
//  2: 500 kHz,
//  3: Reserved]
#define LORA_SPREADING_FACTOR 12 // [SF7..SF12]
#define LORA_CODINGRATE 1 // [1: 4/5,
//  2: 4/6,
//  3: 4/7,
//  4: 4/8]
#define LORA_PREAMBLE_LENGTH 8 // Same for Tx and Rx
#define LORA_SYMBOL_TIMEOUT 0 // Symbols
#define LORA_FIX_LENGTH_PAYLOAD_ON false
#define LORA_IQ_INVERSION_ON false
#define TX_OUTPUT_POWER 20

#define TRX_BUFFER 256
#define INTERVAL_REFRESH_APRS 300000 // 5 minutes
#define INTERVAL_POSITION 900000 // 15 minutes
#define INTERVAL_WEATHER 10000
#define INTERVAL_MPPT 10000
#define INTERVAL_TIME 10000
#define INTERVAL_ALARM_BOX_OPENED 60000
#define DELAY_SCREEN_DISPLAYED 1500
#define TIME_SCREEN_ON 15000

#define APRS_CALLSIGN "F4HVV-15"
#define APRS_PATH "RFONLY"
#define APRS_DESTINATION "F4HVV-10"
#define APRS_SYMBOL 'I'
#define APRS_SYMBOL_TABLE '/'
#define APRS_LATITUDE 45.324863
#define APRS_LONGITUDE 5.605224
#define APRS_COMMENT "Solaire camera + NPR70"
#define APRS_TELEMETRY_PARAMS_SEQUENCE 55
#define APRS_TELEMETRY_EQUATIONS_ENABLED false

#define PIN_DHT GPIO11
#define PIN_WIFI GPIO12
#define PIN_NPR GPIO14
#define PIN_LDR ADC2

#define WATCHDOG_TIMEOUT 80 // 1 minute 20
#define LOW_VOLTAGE 11400
#define LDR_ALARM_LEVEL 1000

extern Logging Log2;

#endif //CUBECELL_MONITORING_CONFIG_H
